-- Supabase publishes every table in the public schema through its REST API, using a key that is
-- meant to be public. NBM never uses that API: the app connects as the database owner, which
-- row level security does not restrict. Enabling it with no policies closes the public API to every
-- table. Add this to any new table too.
ALTER TABLE "AudioRoom" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "AudioRoomMember" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "AuditLog" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "AuthToken" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Campaign" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "CampaignMilestone" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "CampaignUpdate" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ConsentRecord" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ContactRequest" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Contribution" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Disbursement" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "EmailOutbox" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Exhibition" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ExhibitionComment" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ExhibitionMedia" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ExhibitionReaction" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ExhibitionSave" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "MailingSubscriber" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Match" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "MatchUpdate" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "MentorProfile" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "MentorshipApplication" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Milestone" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "NewsArticle" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Notification" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Opportunity" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "PageVersion" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "PaymentEvent" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Report" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Setting" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "SupportEnquiry" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "TeamMember" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Thread" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ThreadMessage" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Upload" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "User" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "UserBlock" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "VolunteerApplication" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "_prisma_migrations" ENABLE ROW LEVEL SECURITY;
