// Server-only object storage for exhibition media, application documents and editorial images.
// Nothing is ever served from storage directly: every read goes through app/api/media/[id],
// which checks that the viewer may see the object first.
//
// Two drivers:
//   r2    — a PRIVATE Cloudflare R2 bucket (S3-compatible). Uploads go straight from the browser
//           to R2 via a presigned PUT URL; reads use a short-lived presigned GET URL.
//   local — files under .localdata/uploads, for development only. Refused when
//           SITE_STAGE=production so a deployment can't silently write to an ephemeral disk.
import { S3Client, HeadObjectCommand, GetObjectCommand, PutObjectCommand, DeleteObjectCommand } from "@aws-sdk/client-s3";
import { getSignedUrl } from "@aws-sdk/s3-request-presigner";
import { createReadStream } from "node:fs";
import { mkdir, open, rm, stat, writeFile } from "node:fs/promises";
import { dirname, resolve, sep } from "node:path";
import { hmac, safeEqual } from "@/lib/tokens";
import { isProductionStage } from "@/lib/config";

const ENDPOINT = process.env.R2_ENDPOINT;
const ACCESS_KEY_ID = process.env.R2_ACCESS_KEY_ID;
const SECRET_ACCESS_KEY = process.env.R2_SECRET_ACCESS_KEY;
const BUCKET = process.env.R2_BUCKET || "";
const LOCAL_ROOT = resolve(process.cwd(), ".localdata/uploads");

export type StorageDriver = "r2" | "local" | "none";

export function storageDriver(): StorageDriver {
  if (ENDPOINT && ACCESS_KEY_ID && SECRET_ACCESS_KEY && BUCKET) return "r2";
  return isProductionStage ? "none" : "local";
}

let client: S3Client | null = null;
function s3(): S3Client {
  if (!client) {
    client = new S3Client({
      region: "auto",
      endpoint: ENDPOINT,
      credentials: { accessKeyId: ACCESS_KEY_ID!, secretAccessKey: SECRET_ACCESS_KEY! }
    });
  }
  return client;
}

/** Keys are generated by us ("purpose/userId/uuid.ext"); anything else is rejected outright. */
function localPath(key: string): string | null {
  if (!/^[a-zA-Z0-9][a-zA-Z0-9/_.-]*$/.test(key) || key.includes("..")) return null;
  const full = resolve(LOCAL_ROOT, key);
  return full.startsWith(LOCAL_ROOT + sep) ? full : null;
}

export function signLocalUpload(uploadId: string, expires: number): string {
  return hmac(`local-upload:${uploadId}:${expires}`);
}

export function verifyLocalUpload(uploadId: string, expires: number, signature: string): boolean {
  return Number.isFinite(expires) && expires > Date.now() && safeEqual(signLocalUpload(uploadId, expires), signature);
}

export type UploadTarget = { url: string; headers: Record<string, string> };

/** A one-time URL the browser can PUT the file to. Valid for 10 minutes. */
export async function createUploadTarget(uploadId: string, key: string, contentType: string): Promise<UploadTarget | { error: string }> {
  const driver = storageDriver();
  if (driver === "none") return { error: "Media storage is not configured yet." };
  if (driver === "local") {
    const expires = Date.now() + 10 * 60 * 1000;
    return { url: `/api/uploads/${uploadId}/local?exp=${expires}&sig=${signLocalUpload(uploadId, expires)}`, headers: { "Content-Type": contentType } };
  }
  try {
    const url = await getSignedUrl(s3(), new PutObjectCommand({ Bucket: BUCKET, Key: key, ContentType: contentType }), { expiresIn: 600 });
    return { url, headers: { "Content-Type": contentType } };
  } catch (err) {
    console.error("createUploadTarget failed:", err);
    return { error: "Could not prepare the upload. Please try again." };
  }
}

/** Server-side write, used by the local upload route and the seed scripts. */
export async function putObject(key: string, body: Uint8Array, contentType: string): Promise<boolean> {
  const driver = storageDriver();
  if (driver === "none") return false;
  if (driver === "local") {
    const path = localPath(key);
    if (!path) return false;
    await mkdir(dirname(path), { recursive: true });
    await writeFile(path, body);
    return true;
  }
  try {
    await s3().send(new PutObjectCommand({ Bucket: BUCKET, Key: key, Body: body, ContentType: contentType }));
    return true;
  } catch (err) {
    console.error("putObject failed:", err);
    return false;
  }
}

/** Reads back what storage actually holds, so we never trust the browser's claims about the file. */
export async function getObjectSize(key: string): Promise<number | null> {
  const driver = storageDriver();
  if (driver === "none") return null;
  try {
    if (driver === "local") {
      const path = localPath(key);
      return path ? (await stat(path)).size : null;
    }
    const head = await s3().send(new HeadObjectCommand({ Bucket: BUCKET, Key: key }));
    return head.ContentLength ?? 0;
  } catch {
    return null;
  }
}

/** `length` bytes starting at `start`: used to check file signatures and read video duration. */
export async function readObjectRange(key: string, start: number, length: number): Promise<Uint8Array | null> {
  const driver = storageDriver();
  if (driver === "none") return null;
  try {
    if (driver === "local") {
      const path = localPath(key);
      if (!path) return null;
      const handle = await open(path, "r");
      try {
        const buffer = Buffer.alloc(length);
        const { bytesRead } = await handle.read(buffer, 0, length, start);
        return buffer.subarray(0, bytesRead);
      } finally {
        await handle.close();
      }
    }
    const res = await s3().send(new GetObjectCommand({ Bucket: BUCKET, Key: key, Range: `bytes=${start}-${start + length - 1}` }));
    return (await res.Body?.transformToByteArray()) ?? null;
  } catch {
    return null;
  }
}

/** R2 only: a short-lived URL for one GET, handed out after the caller has checked the viewer may see it. */
export async function createSignedViewUrl(key: string, expiresIn = 300): Promise<string | null> {
  if (storageDriver() !== "r2") return null;
  try {
    return await getSignedUrl(s3(), new GetObjectCommand({ Bucket: BUCKET, Key: key }), { expiresIn });
  } catch (err) {
    console.error("createSignedViewUrl failed:", err);
    return null;
  }
}

/** Local driver only: a stream over part (or all) of the file, for Range requests. */
export async function openLocalObject(key: string, start?: number, end?: number): Promise<{ stream: ReadableStream<Uint8Array>; size: number } | null> {
  const path = localPath(key);
  if (!path) return null;
  try {
    const { size } = await stat(path);
    const nodeStream = createReadStream(path, start !== undefined ? { start, end } : undefined);
    const stream = new ReadableStream<Uint8Array>({
      start(controller) {
        nodeStream.on("data", (chunk) => controller.enqueue(new Uint8Array(chunk as Buffer)));
        nodeStream.on("end", () => controller.close());
        nodeStream.on("error", (err) => controller.error(err));
      },
      cancel() {
        nodeStream.destroy();
      }
    });
    return { stream, size };
  } catch {
    return null;
  }
}

/** Best-effort delete; failures are logged, not thrown, so cleanup never blocks the caller. */
export async function deleteObject(key: string): Promise<void> {
  const driver = storageDriver();
  try {
    if (driver === "local") {
      const path = localPath(key);
      if (path) await rm(path, { force: true });
    } else if (driver === "r2") {
      await s3().send(new DeleteObjectCommand({ Bucket: BUCKET, Key: key }));
    }
  } catch (err) {
    console.error("deleteObject threw:", key, err);
  }
}
